apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  namespace: data
spec:
  replicas: 1
  selector: { matchLabels: { app: products-api } }
  template:
    metadata: { labels: { app: products-api } }
    spec:
      serviceAccountName: dagster-user-code
      containers:
        - name: api
          image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
          env:
            - name: WEATHER_RESULTS_BUCKET
              value: "dagster-weather-products"
            - name: WEATHER_RESULTS_PREFIX
              value: "weather-products/"
          ports: [{ containerPort: 80 }]
