apiVersion: v1
kind: Service
metadata:
  name: products-api
  namespace: data
spec:
  selector: { app: products-api }
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: ClusterIP
