apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: products-api
  namespace: monitoring
  labels:
    release: kps  # Required for Prometheus to discover this ServiceMonitor
spec:
  namespaceSelector:
    matchNames:
      - data
  selector:
    matchLabels:
      app: products-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
